Empleados y base
noosqui/FerreteriaMaresa pull request #7
Opened 2021-03-02 21:50 UTC by Danny7821

Solución de algunos errores.

2021-03-02 22:08 UTC, noosqui commented on FerreteriaMaresa/Datos/DAT_Empleados.cs
>              comando.Parameters.AddWithValue("@idempleado", idempleado);
No es necesario enviar parámetro, esto se puede hacer desde adentro

2021-03-02 22:09 UTC, noosqui commented on FerreteriaMaresa/Datos/DAT_Empleados.cs
>              comando.Parameters.AddWithValue("@idempleado", idempleado);
Consideren hacer un procedimiento para recontratar empleado (no tan necesario ahora)

2021-03-03 03:42 UTC, noosqui commented on FerreteriaMaresa/Datos/DAT_Empleados.cs
>          private DAT_Conexion conexion = new DAT_Conexion();
en esta parte programado solo recorda quitar los campos repetidos y ponerlos afuera, ademas de cerrar la conexion luego de cada proceso

2021-03-03 04:01 UTC, noosqui commented on FerreteriaMaresa/Datos/Ferreteria Maresa DB.sql
>  create table TipoPago
No hay relacion en: detallecompra-factura compra, FacturaVenta-Detalleventa
cambiar la parte de direccion de bancos

2021-03-03 04:08 UTC, noosqui commented on FerreteriaMaresa/Datos/Procedimientos Almacenados.sql
> +
La idea de este esta excelente. pero creo que seria mejor verlos todos y se pueden diferenciar a nivel de programacion si se quiere ver los activos, inactivos, o todos. Si no consideran asi diganme

2021-03-03 04:08 UTC, noosqui commented on FerreteriaMaresa/Datos/Procedimientos Almacenados.sql
> +--Buscar Empleado
Al igual con empleado se puede hacer una busqueda en general y se puede especificar a nivel de programacion

2021-03-03 17:55 UTC, Danny7821 commented
Me parece mejor como decís vos, no lo tome a consideración que se puede
hacer a nivel de programación, me parece mejor porque así se tiene mejor
control de lo que se quiere ver, lo dejare corregido

El mar., 2 mar. 2021 10:08 p. m., noosqui <notifications@github.com>
escribió:

> *@noosqui* commented on this pull request.
> ------------------------------
>
> In FerreteriaMaresa/Datos/Procedimientos Almacenados.sql
> <https://github.com/noosqui/FerreteriaMaresa/pull/7#discussion_r586092171>
> :
>
> > +	@contrasenia as nvarchar(80)
> +	as
> +	   update Empleados set id_empleado=@idEmpleado, nom_empleado=@nombreEmpleado, apellido_empleado=@apellidoEmpleado, correo_empleado=@correoEmpleado, telefono_empleado=@telEmpleado, direccion=@direccion, ciudad=@ciudad, region=@region, codigo_postal=@codigo_postal, pais=@pais, id_rol_empleado=@id_rol_empleado, fnacimiento_empleado=@fnacimiento_empleado, Estado=@estado, contrasenia=@contrasenia
> +	   where id_empleado=@idEmpleado
> +go
> +
> +
> +--Despedir Empleado
> + create procedure Despedir_Empleado
> +@idEmpleado as nvarchar(13)
> +as
> +	   update Empleados set Estado = 'Despedido'
> +	   where id_empleado = @idEmpleado
> +
> +go
> +
>
> La idea de este esta excelente. pero creo que seria mejor verlos todos y
> se pueden diferenciar a nivel de programacion si se quiere ver los activos,
> inactivos, o todos. Si no consideran asi diganme
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/noosqui/FerreteriaMaresa/pull/7#pullrequestreview-602489879>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APW2WVCQKNGNCGJ5YJMAKMLTBWY3DANCNFSM4YPZTEQA>
> .
>

2021-03-05 03:54 UTC, noosqui commented on FerreteriaMaresa/Datos/DAT_Empleados.cs
>              SqlDataReader lee;
te falto este

2021-03-05 04:01 UTC, noosqui requested changes
Note que en la tabla empleados se guarda la contraseña, no se si arreglaron eso 🤔

2021-03-05 07:25 UTC, Danny7821 commented on FerreteriaMaresa/Datos/DAT_Empleados.cs
>              SqlDataReader lee;
> te falto este

Listo, instancie el SqlDataReader arriba (no se si tambien querias que moviera el  lee = comando.ExecuteReader(); porque ese me daba error de las formas que lo quize mover supuse que ese no quedaba ahi), tambien ya quedo usuario y empleados relacionadas por id_empleado y deje la contraseña en la tabla usuario

2021-03-05 15:36 UTC, closed without merging